language: swift
osx_image: xcode11.5
xcode_workspace: Hackers.xcworkspace
xcode_scheme: Hackers
before_install:
- gem install xcpretty
- gem update cocoapods
- gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
install:
- brew install swiftlint
- bundle install
- bundle update fastlane
- pod install --project-directory=$TRAVIS_BUILD_DIR --repo-update
jobs:
  include:
    - stage: "Tests"
      name: "UI Tests"
      script:
        - bundle exec fastlane test
    - stage: "Static Analysis"
      name: "SwiftLint"
      script:
        - bundle exec fastlane lint
    - stage: "Build"
      name: "Release"
      script:
        - bundle exec fastlane build