language: swift
osx_image: xcode11.5
xcode_workspace: Hackers.xcworkspace
xcode_scheme: Hackers
before_install:
- gem update cocoapods
- gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
install:
- bundle install
- pod install --project-directory=$TRAVIS_BUILD_DIR --repo-update
jobs:
  include:
    # UI tests disable on Travis until data can be mocked to prevent timeouts
    # - stage: "Tests"
    #   name: "UI Tests"
    #   script:
    #     - bundle exec fastlane test
    - stage: "Static Analysis"
      name: "SwiftLint"
      before_install: false
      script:
        - brew install swiftlint
        - bundle exec fastlane lint
    - stage: "Build"
      name: "Release"
      script:
        - bundle exec fastlane build
after_success: travis_wait 5